#!/bin/bash

USERID=$(id -u)

if [ $USERID -ne 0 ]; then
    echo "ERROR :: Please run this command in root privilage"
    exit 1 # failure is other than 0
fi

VALIDATE (){
    if [ $1 -ne 0 ]; then
        echo "ERROR :: Installing $2 is Failure"
        exit 1 # failure is other than 0
    else
        echo "installing $2 is SUCCESS"
    fi
}

dnf install mysql -y
VALIDATE $? "mysql"

dnf install nginx -y
VALIDATE $? "Nginx"

dnf install python3 -y
VALIDATE $? "Python3"